### ISSUE TITLE
Example command fails with error

### ISSUE THREAD

**Issue by nmwsharp** [ishit/nie#1]
Hi! Thanks for sharing this code, and great paper :)

Just an FYI, I tried grabbing the code, resolving dependencies, and running the example command `python3 main.py --config config/vbunny.yaml`.

It ran fine initially, but after many iterations failed with a tensor shape error:

```
...
Iter: 736
Iter: 737
Iter: 738
Iter: 739
Iter: 740
Traceback (most recent call last):
  File "nie/main.py", line 168, in <module>
    main(config)
  File "nie/main.py", line 96, in main
    faces.data[:f] = torch.from_numpy(np.ascontiguousarray(faces_np))
RuntimeError: The expanded size of the tensor (950000) must match the existing size (1094172) at non-singleton dimension 0.  Target sizes: [950000, 3].  Tensor sizes: [1094172, 3]
```

I haven't tried debugging in to the issue at all, but wanted to let you know.

**Comment by ishit** [comment]
Added a docker image to replicate the experiments:
[gitlab-registry.nrp-nautilus.io/ibmehta/lse](http://gitlab-registry.nrp-nautilus.io/ibmehta/lse)
