### ISSUE TITLE
Fails in shapenet chair

### ISSUE THREAD

**Issue by XinYu-Andy** [ishit/nie#2]
Hi, 
Thanks for your awesome work!
I just try to use your method to reconstruct a chair object from its 100 view images, but the final result seems to be not good (as shown below).
I use the configuration setting in 'genus6.yaml', could you please give some advice?
<img width="337" alt="image" src="https://user-images.githubusercontent.com/60741299/198190879-cf55da05-15d8-48c8-8249-123197e60a88.png">

**Comment by XinYu-Andy** [comment]
> Hi, Thanks for your awesome work! I just try to use your method to reconstruct a chair object from its 100 view images, but the final result seems to be not good (as shown below). I use the configuration setting in 'genus6.yaml', could you please give some advice? <img alt="image" width="337" src="https://user-images.githubusercontent.com/60741299/198190879-cf55da05-15d8-48c8-8249-123197e60a88.png">

Some views of the gt object are shown below.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/60741299/198191303-5bab54a4-743c-492d-9fcb-4fbd8978bd35.png">

**Comment by ishit** [comment]
Do you mind sharing your ply/obj file?

**Comment by XinYu-Andy** [comment]
> Do you mind sharing your ply/obj file?

Sure~ 
The .obj can be downloaded [here](https://drive.google.com/file/d/1MHc5136vkzmCQTHFm6jk-EvcAeA-fQg6/view?usp=share_link)
Thank you!

**Comment by XinYu-Andy** [comment]
> Do you mind sharing your ply/obj file?

hello~ Is there some progress?

**Comment by ishit** [comment]
Sorry about the late response. Like several cases in inverse rendering pipeline this seems like it's stuck in a local minimum. Things I'd try is changing the parameterization of the initial shape to not be biased towards high frequency features (change \omega to 30 in siren). Another thing to try is tweaking the laplace_lam parameter.
